"""Shared generator utilities."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from fw_audit import __version__
from fw_audit.models import Classification, Listener


def ruleset_header(platform: str, hostname: str) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    return (
        f"# Generated by fw-audit {__version__} at {ts}\n"
        f"# Platform: {platform} | Host: {hostname}\n"
        f"# CIS 9.4 / NIST SC-7(5): default-deny, allow-by-exception\n"
        f"# REVIEW BEFORE APPLY — home-lab use only\n"
    )


def listeners_to_allow(
    listeners: list[Listener], policy: dict[str, Any], *, init_mode: bool = False
) -> list[Listener]:
    """Return listeners that should receive explicit allow rules."""
    if init_mode or policy.get("init_baseline"):
        return [
            ln
            for ln in listeners
            if ln.classification in (Classification.PREFERRED, Classification.RISKY)
            and ln.state != "planned-outbound"
        ]

    approved = policy.get("approved_risky", [])
    allowed: list[Listener] = []
    for ln in listeners:
        if ln.state == "planned-outbound":
            continue
        if ln.classification == Classification.PREFERRED:
            allowed.append(ln)
        elif ln.classification == Classification.RISKY:
            key = f"{ln.protocol}/{ln.port}"
            approved_ports = {
                (str(a.get("proto", "")).lower(), int(a.get("port", -1)))
                if isinstance(a, dict)
                else (key.split("/")[0], int(key.split("/")[1]))
                for a in approved
            }
            if (ln.protocol.lower(), ln.port) in approved_ports or key in approved:
                allowed.append(ln)
    return allowed
